/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>/packages', '<rootDir>/services'],
  testMatch: ['**/*.test.ts', '**/*.spec.ts'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: 'tsconfig.json',
      isolatedModules: true,
    }],
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@/(.*)$': '<rootDir>/apps/dashboard/src/$1',
    '^@whatsapp-ai/config$': '<rootDir>/packages/config/src/index.ts',
    '^@whatsapp-ai/common$': '<rootDir>/packages/common/src/index.ts',
    '^@whatsapp-ai/logger$': '<rootDir>/packages/logger/src/index.ts',
    '^@whatsapp-ai/database$': '<rootDir>/packages/database/src/index.ts',
    '^@whatsapp-ai/events$': '<rootDir>/packages/events/src/index.ts',
    '^@whatsapp-ai/queue$': '<rootDir>/packages/queue/src/index.ts',
    '^@whatsapp-ai/sentry$': '<rootDir>/packages/sentry/src/index.ts',
    '^@whatsapp-ai/whatsapp$': '<rootDir>/packages/whatsapp/src/index.ts',
    '^@whatsapp-ai/gdpr$': '<rootDir>/packages/gdpr/src/index.ts',
    '^@whatsapp-ai/cdn$': '<rootDir>/packages/cdn/src/index.ts',
    '^@whatsapp-ai/monitoring$': '<rootDir>/packages/monitoring/src/index.ts',
    '^@whatsapp-ai/ai$': '<rootDir>/packages/ai/src/index.ts',
    '^@whatsapp-ai/sdk$': '<rootDir>/packages/sdk/src/index.ts',
    '^@whatsapp-ai/(.*)$': '<rootDir>/packages/$1/src',
    '^express-rate-limit$': '<rootDir>/tests/unit/__mocks__/express-rate-limit.js',
  },
  collectCoverageFrom: [
    'packages/*/src/**/*.ts',
    'services/*/src/**/*.ts',
    'apps/*/src/**/*.ts',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/dist/**',
  ],
  coverageDirectory: 'coverage',
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 10000,
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  passWithNoTests: true,
};
